### PR TITLE
Update miniz library

### PR DESCRIPTION
**Pull request by janisozaur**
This is to trigger internal verification discussed here: https://github.com/GPUOpen-LibrariesAndSDKs/Anvil/pull/17#issuecomment-289681296

### CODE REVIEW

**Comment by DominikWitczakAMD** [comment]
I've passed this change over for further analysis.

**Comment by DominikWitczakAMD** [comment]
@janisozaur : I know it's been a lot of time but when you get a free second, can you please resolve the conflicts? Thanks

**Comment by janisozaur** [comment]
Sure, I'll take care of that in the next few days.

**Comment by DominikWitczakAMD** [comment]
Not much traffic here, closing. Please feel free to reopen the PR if you feel this change is still relevant.

**Pull request closed without merging**
